[2025-09-05T22:53:46.828-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-05T22:53:46.951-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_FLIGHTS.validate manual__2025-09-06T01:51:51.730882+00:00 [queued]>
[2025-09-05T22:53:47.045-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_FLIGHTS.validate manual__2025-09-06T01:51:51.730882+00:00 [queued]>
[2025-09-05T22:53:47.051-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-05T22:53:47.962-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate> on 2025-09-06 01:51:51.730882+00:00
[2025-09-05T22:53:47.988-0300] {standard_task_runner.py:63} INFO - Started process 46740 to run task
[2025-09-05T22:53:48.008-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_FLIGHTS', 'validate', 'manual__2025-09-06T01:51:51.730882+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ETL_FLIGHTS.py', '--cfg-path', '/tmp/tmpry6_8np_']
[2025-09-05T22:53:48.013-0300] {standard_task_runner.py:91} INFO - Job 12: Subtask validate
[2025-09-05T22:53:48.510-0300] {task_command.py:426} INFO - Running <TaskInstance: ETL_FLIGHTS.validate manual__2025-09-06T01:51:51.730882+00:00 [running]> on host sebastian-Aspire-A515-54
[2025-09-05T22:53:49.448-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL_FLIGHTS' AIRFLOW_CTX_TASK_ID='validate' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T01:51:51.730882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T01:51:51.730882+00:00'
[2025-09-05T22:53:49.458-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-05T22:53:49.502-0300] {ETL_FLIGHTS.py:90} INFO - validate: OK, inserted 100 rows
[2025-09-05T22:53:49.504-0300] {python.py:237} INFO - Done. Returned value was: None
[2025-09-05T22:53:49.506-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-05T22:53:49.542-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_FLIGHTS, task_id=validate, run_id=manual__2025-09-06T01:51:51.730882+00:00, execution_date=20250906T015151, start_date=20250906T015346, end_date=20250906T015349
[2025-09-05T22:53:49.915-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-05T22:53:50.013-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-05T22:53:50.017-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
